### ISSUE TITLE
A suggestion indeed

### ISSUE THREAD

**Issue by smartagent47** [substratum/home#4]
Being a part of **Front End**, i would just like to suggest you some small things. 

* I think the theme thumbnails should be links instead of inserting the link icon inside the thumbnail box. That looks pretty decent i guess.

* The thumbnails can be a great carousel because the stacks of thumbnails(large in number) dont look good on a mobile platform. A lot has to be scrolled. 

* Maybe on a desktop, the navigation bar should be sticky i.e it floats on the top when scrolled so that when the user wants to navigate to another section, user might not have to go up first and then navigate which kindof disturbs the UX. 

I am sorry if any of the points mentioned or all are incorrect as i am not a perfect or master in front end. 

> **_"A great project by great developers !"_**

Thanks

**Comment by nicholaschum** [comment]
Thank you for your suggestions. As we are using a template, it would take some time for us to conduct these changes, especially regarding layouts. We will keep this in mind, however!
